# docker-compose.yml
version: "3"
services:
  app:
    build: .
    environment:
      DB_HOST: host.docker.internal
    ports:
      - "3000:3000"
    volumes:
      - .:/app/
      - /app/node_modules
